spring:
  application:
    name: mua-service
  datasource:
    url: jdbc:postgresql://localhost:5432/jasafy
    username: postgres
    password: postgrespass
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 8092
  forward-headers-strategy: framework
  servlet:
    context-path: /api/mua
    encoding:
      charset: utf-8
      force-response: true